version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - TZ=Asia/Bangkok

  vdo-factory:
    image: faizalj/ai-toolstack-vdo-factory:latest
    container_name: vdo-factory
    restart: always
    ports:
      - "8000:8000"
    # GPU Configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # ถ้ามี ENV อื่น เช่น API KEY ให้ใส่เพิ่มตรงนี้

volumes:
  n8n_data: